version: '3.7'

services:
  persona-testing:
    build:
      context: ./persona/persona-api
      dockerfile: Dockerfile
    image: persona-testing:1.0
    ports:
      - 9010:9010
    depends_on:
      - eureka
      - config
      - zuul
  archivo-testing:
    build:
      context: ./archivo/archivo-api
      dockerfile: Dockerfile
    image: archivo-testing:1.0
    ports:
      - 9020:9020
    depends_on:
      - eureka
      - config
      - zuul
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: eureka:1.0
    ports:
      - 8761:8761
  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    image: zuul:1.0
    ports:
      - 8000:8000
    depends_on:
      - config
  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    image: config:1.0
    ports:
      - 8888:8888
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin:1.0
    ports:
      - 8084:8084
  seguridad:
    build:
      context: ./seguridad/seguridad-api
      dockerfile: Dockerfile
    image: seguridad:1.0
    ports:
      - 8090:8090
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200