management:
  endpoints:
    web:
      exposure:
        include: env

jwt:
  secretKey: ${KEYSECRET_SECURITY:SjLNct19ONkWJIw4OW4EFz8V8KUNLiQ9CU_We2nUsLg}
  prefix: ${PREFIX_SECURITY:Bearer}
  expiraInDays: ${EXPIRA_DAYS_SECURITY:14}