spring:
  database:
    url: jdbc:h2:mem:testdb
    user: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update